name: Upload large SC2 maps

on:
  push:
    branches: ["main"]     # or your default branch

permissions:
  contents: write          # needed for release upload

jobs:
  upload-big-maps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false       # we’re not using Git-LFS anymore

      # run the manifest script (updates maps.json)
      - name: Regenerate maps.json
        run: python .github/scripts/update_maps_json.py

      # find any maps flagged "release_asset": true
      - id: list
        run: |
          python - <<'PY'
          import json,glob,os,sys,pathlib,shlex
          data=json.load(open("maps.json"))
          files=[ m["name"]
                  for c in data
                  for m in c["maps"]
                  if m.get("release_asset") ]
          print("::set-output name=files::" + " ".join(shlex.quote(f) for f in files))
          PY

      # create release tag if it doesn't exist
      - uses: softprops/action-gh-release@v1
        if: steps.list.outputs.files != ''
        with:
          tag_name: maps-assets
          name: Maps Assets
          body: "Auto-uploaded large .SC2Map files"
          draft: false
          prerelease: false

      # upload each large file
      - name: Upload assets
        if: steps.list.outputs.files != ''
        run: |
          for f in ${FILES}; do
            gh release upload maps-assets "campaigns/**/$f" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: ${{ steps.list.outputs.files }}

      # commit updated maps.json (URL fields now point at release)
      - name: Commit manifest
        run: |
          git config user.name  github-actions
          git config user.email noreply@github.com
          git add maps.json
          git commit -m "ci: update maps.json with release URLs" || echo "no change"
          git push

