name: Auto-update maps.json

on:
  push:
    branches: [ main ]
    paths:            # trigger only when SC2Map files change
      - '**/*.SC2Map'

permissions:
  contents: write     

jobs:
  regen-manifest:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Regenerate maps.json
        run: python .github/scripts/update_maps_json.py

      - name: Commit and push
        run: |
          if git diff --quiet -- maps.json; then
            echo "maps.json unchanged – nothing to commit"
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add maps.json
            git commit -m "ci: auto-update maps.json"
            git push origin HEAD:${{ github.ref }}
          fi
